# Exercises and Examples in Python with NumPy

## Purpose
This notebook aims to provide practice using NumPy and Python through guided examples and practical exercises. Topics include indexing, slicing, matrix operations, function definitions, and optimization using gradient descent.





# 1 Examples: NumPy
1. Basic Indexing: 

Descripción: Accede al elemento con índice 2 del arreglo arr, que es 30 (recordando que la indexación comienza desde 0).



In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[2]) # Output: 30

30


2. Slicing (Corte)

Descripción: Extrae una sub-secuencia del arreglo desde el índice 1 hasta el 3 (el índice 4 no se incluye). El resultado es [20, 30, 40].

In [3]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4]) # Output: [20 30 40]


[20 30 40]


3. Indexing 2D Arrays

Descripción: Accede al elemento ubicado en la segunda fila y tercera columna del arreglo 2D, que es 6.

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1, 2]) # Output: 6

6


4. Slicing (Corte) de Arrays 2D

Descripción: Extrae una submatriz que contiene las dos primeras filas y desde la segunda columna en adelante.



In [5]:
print(arr[:2, 1:]) # Output: [[2 3] [5 6]]


[[2 3]
 [5 6]]


5. Indexación de Tensores 3D

Descripción:

-tensor[1, 0, 2] accede al elemento en el segundo bloque, primera fila, tercera columna → valor: 9.

-tensor[1] devuelve el bloque 2D completo ubicado en la posición 1 (segundo bloque).

In [6]:
tensor = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]],
[[13, 14, 15], [16, 17, 18]]])

# Access specific elements
print(tensor[1, 0, 2]) # Output: 9
# Access an entire "slice" (2D submatrix)
print(tensor[1]) # Output: [[ 7 8 9] [10 11 12]]

9
[[ 7  8  9]
 [10 11 12]]


6. Slicing de un Tensor 3D

Descripción: Muestra cómo obtener cortes a lo largo de distintas dimensiones (bloques, filas, columnas) en un tensor 3D.



In [7]:
tensor = np.arange(27).reshape(3, 3, 3)
# Slice along the first dimension
print(tensor[1]) # Output: 3x3 submatrix
# Slice along the second dimension
print(tensor[:, 1, :]) # Output: 3x3 submatrix
# Slice along the third dimension
print(tensor[:, :, 2]) # Output: 3x3 submatrix

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]


7. Indexación de Tensor 4D

Descripción:

tensor[1, 2, 0, 3] accede al valor en el segundo bloque, tercera "capa"(matrices), primera fila, cuarta columna → valor: 47.

tensor[1, 2] devuelve un sub-tensor de tamaño 2x4 (una sección tridimensional del tensor original).



In [8]:
tensor = np.arange(48).reshape(2, 3, 2, 4)
# Access specific elements
print(tensor[1, 2, 0, 3]) # Output: 47
# Access a whole "block" (3D sub-tensor)
print(tensor[1, 2]) # Output: 2x4x3 sub-tensor

43
[[40 41 42 43]
 [44 45 46 47]]



8. Slicing en Tensor 4D

Descripción:

tensor[1]: todo el segundo bloque.

tensor[:, 2, :, :]: la tercera "capa" (índice 2) de todos los bloques.

tensor[:, :, 0, :]: la primera "fila interna" de todos los bloques.

In [12]:
tensor = np.arange(48).reshape(2, 3, 2, 4)
# Slice along the first dimension
print(tensor[1]) # Output: 3x2x4 sub-tensor
# Slice along the second dimension
print(tensor[:, 2, :, :]) # Output: 2x2x4 sub-tensor
# Slice along the third dimension
print(tensor[:, :, 0, :]) # Output: 2x3x4 sub-tensor

[[[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]]
[[[16 17 18 19]
  [20 21 22 23]]

 [[40 41 42 43]
  [44 45 46 47]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]
  [16 17 18 19]]

 [[24 25 26 27]
  [32 33 34 35]
  [40 41 42 43]]]


9. Suma de Matrices

Descripción: Se suman las matrices A y B elemento por elemento.

In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = A + B
print(result)


[[ 6  8]
 [10 12]]


10. Multiplicación de Matrices

Descripción: Se realiza la multiplicación matricial estándar.

In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


11. Transpuesta de una Matriz

Descripción: La función np.transpose invierte filas y columnas.

In [13]:
A = np.array([[1, 2], [3, 4]])
result = np.transpose(A)
print(result)

[[1 3]
 [2 4]]


12. Determinante e Inversa

Descripción:

np.linalg.det(A): calcula el determinante.

np.linalg.inv(A): calcula la inversa de la matriz A.



In [14]:
A = np.array([[1, 2], [3, 4]])
det = np.linalg.det(A)
inverse = np.linalg.inv(A)
print("Determinant:", det)
print("Inverse:\n", inverse)

Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


13. Valores y Vectores Propios (Eigenvalues/Eigenvectors)

Descripción: Calcula los autovalores y autovectores de la matriz A, que son importantes en álgebra lineal y machine learning.



In [23]:
A = np.array([[1, -1], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [2.00000002 1.99999998]
Eigenvectors:
 [[-0.70710677 -0.70710679]
 [ 0.70710679  0.70710677]]


14. Resolver Sistemas de Ecuaciones Lineales

Descripción: Resuelve el sistema de ecuaciones lineales Ax = b.

In [26]:
A = np.array([[2, 1], [1, 1]])
b = np.array([3,2])
solution = np.linalg.solve(A, b)
print("Solution:", solution)

Solution: [1. 1.]


15. Descenso por Gradiente (Regresión Lineal)

Descripción:

Se genera un dataset artificial para regresión lineal.

Se entrena un modelo usando descenso por gradiente.

theta son los parámetros óptimos del modelo (intercepto y pendiente).

El objetivo es minimizar el error cuadrático medio (MSE).

In [147]:
# Generate some sample data
np.random.seed(0)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)
# Add bias term to X
X_b = np.c_[np.ones([100, 1]), X]
# Hyperparameters
learning_rate = 0.1
n_iterations = 1000
# Initialize the parameters
theta = np.random.randn(2, 1) 
# Gradient Descent
for iteration in range(n_iterations):
  
    gradients = 2 / 100 * X_b.T.dot(X_b.dot(theta) - y)

    theta = theta - learning_rate * gradients

print("Final theta:", theta)

Final theta: [[4.22215108]
 [2.96846751]]


# 2 Examples: Python functions and classes

1. Función Simple

Descripción: Esta función recibe un nombre y devuelve un saludo personalizado. Simplemente concatena "Hello, " con el nombre proporcionado.



In [149]:
def greet(name):
    return "Hello, " + name + "!"
print(greet("Ana")) # Output: Hello, Ana!

Hello, Ana!


2. Función con Parámetros y Retorno

Descripción: Suma dos números y devuelve el resultado. Los parámetros a y b son sumados y el resultado se retorna.

In [150]:
def add_numbers(a, b):
    sum = a + b
    return sum

result = add_numbers(5, 7)
print(result)  # Output: 12

12


3. Función con Parámetro por Defecto

Descripción: Calcula la potencia de un número. Si no se proporciona el exponente, se usa el valor por defecto 2.

In [151]:
def power(base, exponent=2):
    return base ** exponent

print(power(3))      # Output: 9
print(power(2, 3))   # Output: 8

9
8


4. Función con Múltiples Retornos

Descripción: Devuelve el valor mínimo y máximo de una lista de números usando min() y max().

In [152]:
def min_max(numbers):
    return min(numbers), max(numbers)

nums = [4, 9, 2, 7, 5]
minimum, maximum = min_max(nums)
print(minimum, maximum)  # Output: 2 9

2 9


5. Función con Docstring

Descripción: Esta función tiene una cadena de documentación (docstring) que explica cómo usarla. Calcula el área multiplicando largo por ancho.

In [153]:
def area_of_rectangle(length, width):
    """
    Calcula el área de un rectángulo.
    
    Args:
        length (float): Longitud del rectángulo.
        width (float): Ancho del rectángulo.
    
    Returns:
        float: Área del rectángulo.
    """
    return length * width

6. Creación de una Clase Simple

Descripción: Se define una clase Dog con atributos y un método. El método bark() imprime un mensaje cuando el perro ladra.



In [169]:
class Dog:
    def __init__(self, name, age):
        self.name = name
        self.age = age
      

    def bark(self):
        print(f"{self.name} is barking!")

# Crear una instancia
dog1 = Dog("Buddy", 3)
dog1.bark()  # Output: Buddy is barking!

Buddy is barking!


7. Clase con Métodos y Atributos Adicionales

Descripción: Se crea una clase Student que permite agregar calificaciones y calcular el promedio. Usa listas y operaciones básicas.



In [184]:
class Student:
	def __init__(self, name, age):
		self.name = name
		self.age = age
		self.grades = []

	def add_grade(self, grade):
		self.grades.append(grade)

	def get_average_grade(self):
		return sum(self.grades) / len(self.grades)

# Create a Student instance and add grades
student1 = Student("Alice", 18)
student1.add_grade(85)
student1.add_grade(92)
average_grade = student1.get_average_grade()
print(f"{student1.name}’s average grade: {average_grade}")

Alice’s average grade: 88.5


8. Herencia en Clases

Descripción: Se utiliza herencia. Cat y Dog heredan de Animal y sobrescriben el método speak() con su propio comportamiento.

In [180]:
class Animal:
    def __init__(self, name):
        self.name = name

    def speak(self):
        pass  # Método a sobrescribir

class Cat(Animal):
    def speak(self):
        print(f"{self.name} says Meow!")

class Dog(Animal):
    def speak(self):
        print(f"{self.name} says Woof!")

# Instancias
cat = Cat("Whiskers")
dog = Dog("Buddy")

cat.speak()  # Output: Whiskers says Meow!
dog.speak()  # Output: Buddy says Woof!

Whiskers says Meow!
Buddy says Woof!
