# Exercises and Examples in Python with NumPy

## Purpose
This notebook aims to provide practice using NumPy and Python through guided examples and practical exercises. Topics include indexing, slicing, matrix operations, function definitions, and optimization using gradient descent.





# 1 Examples: NumPy
1.1. Basic Indexing: 

Descripción: Accede al elemento con índice 2 del arreglo arr, que es 30 (recordando que la indexación comienza desde 0).



In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[2]) # Output: 30

30


1.2. Slicing (Corte)

Descripción: Extrae una sub-secuencia del arreglo desde el índice 1 hasta el 3 (el índice 4 no se incluye). El resultado es [20, 30, 40].

In [7]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4]) # Output: [20 30 40]


[20 30 40]


1.3. Indexing 2D Arrays

Descripción: Accede al elemento ubicado en la segunda fila y tercera columna del arreglo 2D, que es 6.

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1, 2]) # Output: 6

6


1.4. Slicing (Corte) de Arrays 2D

Descripción: Extrae una submatriz que contiene las dos primeras filas y desde la segunda columna en adelante.



In [25]:
print(arr[:2, 1:]) # Output: [[2 3] [5 6]]


[[2 3]
 [5 6]]


1.5. Indexación de Tensores 3D

Descripción:

-tensor[1, 0, 2] accede al elemento en el segundo bloque, primera fila, tercera columna → valor: 9.

-tensor[1] devuelve el bloque 2D completo ubicado en la posición 1 (segundo bloque).

In [ ]:
tensor = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]],
[[13, 14, 15], [16, 17, 18]]])

# Access specific elements
print(tensor[1, 0, 2]) # Output: 9
# Access an entire "slice" (2D submatrix)
print(tensor[1]) # Output: [[ 7 8 9] [10 11 12]]

9
[[ 7  8  9]
 [10 11 12]]


1.6. Slicing de un Tensor 3D

Descripción: Muestra cómo obtener cortes a lo largo de distintas dimensiones (bloques, filas, columnas) en un tensor 3D.



In [35]:
tensor = np.arange(27).reshape(3, 3, 3)
# Slice along the first dimension
print(tensor[1]) # Output: 3x3 submatrix
# Slice along the second dimension
print(tensor[:, 1, :]) # Output: 3x3 submatrix
# Slice along the third dimension
print(tensor[:, :, 2]) # Output: 3x3 submatrix

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]


1.7. Indexación de Tensor 4D

Descripción:

tensor[1, 2, 0, 3] accede al valor en el segundo bloque, tercera "capa"(matrices), primera fila, cuarta columna → valor: 47.

tensor[1, 2] devuelve un sub-tensor de tamaño 2x4 (una sección tridimensional del tensor original).



In [36]:
tensor = np.arange(48).reshape(2, 3, 2, 4)
# Access specific elements
print(tensor[1, 2, 0, 3]) # Output: 47
# Access a whole "block" (3D sub-tensor)
print(tensor[1, 2]) # Output: 2x4x3 sub-tensor

43
[[40 41 42 43]
 [44 45 46 47]]
